### ISSUE TITLE
Activity - Add possibility to choose image from preset of images

### ISSUE THREAD

**Issue by I-Stork** [Loefbijter/web#17]
Right now people who create activitities have to give an URL for the image, however this is not ideal as we have no place to host these images yet. Additionally, this means that people have to find these images and upload them. 

A better solution would be to have a preset of images and if someone creates an activity (s)he can choose an image from this preset. To accomplish this, a couple of things have to be done:
- Collect images from various events (Borrels, Gala, Kerstdiner, Ouderdag, Batavierenrace), these can be found in "Het fotoarchief (google drive)"
- Store all of these images somewhere (e.g. Github).
- Build functionality so that you can choose one of these images when creating an event.

**Comment by dutchmartin** [comment]
On https://github.com/Loefbijter/images/tree/master/evenementen you can see various images that are cherry picked from the promotion images album. They are still quite big in size, so cropping and resizing them to 500 pixels wide is still a todo. Be sure to  also throw them into a image compressor so the file size is fairly small. For reference, see outer images in the repo.
